### ISSUE TITLE
rthunder: inputs are not registered

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#1024]
It looks like at least the coin inputs are not being read

**Comment by rp-jt** [comment]
Fixed in 4f664dfa890527293f1ee357ab3409f84e793a54

**Comment by JanGunheD** [comment]
But I still have the same problem with the newest version, at least in Wonder Momo and Rolling Thunder.

**Comment by jotego** [comment]
@JanGunheD , please follow [these notes](https://github.com/jotego/jtbin/wiki/Why-I-only-see-the-on-screen-credits%3F)

**Comment by JanGunheD** [comment]
> [@JanGunheD](https://github.com/JanGunheD) , please follow [these notes](https://github.com/jotego/jtbin/wiki/Why-I-only-see-the-on-screen-credits%3F)

The newest beta key solved it, thanks!

**Comment by shuffle5** [comment]
I'm still having the same problem with rolling thunder and now pack and button / joystick not registering

**Comment by jotego** [comment]
@shuffle5, please follow [these notes](https://github.com/jotego/jtbin/wiki/Why-I-only-see-the-on-screen-credits%3F)
